const FAENAS =[
    //Lucia
    {
    fecha: "2023-07-13",
      nombre: "Lucia",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-07-14",
      nombre: "Lucia",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-07-20",
      nombre: "Lucia",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-07-21",
      nombre: "Lucia",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-07-29",
      nombre: "Lucia",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-07-30",
      nombre: "Lucia",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-08-05",
      nombre: "Lucia",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-08-06",
      nombre: "Lucia",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-08-12",
      nombre: "Lucia",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-08-13",
      nombre: "Lucia",
      asistencia: false,
      pagada: true,
    },

    {
      fecha: "2023-08-19",
      nombre: "Lucia",
      asistencia: false,
      pagada: false,
    },
    {
      fecha: "2023-08-20",
      nombre: "Lucia",
      asistencia: false,
      pagada: false,
    },
    {
      fecha: "2023-08-26",
      nombre: "Lucia",
      asistencia: false,
      pagada: false,
    },
    {
      fecha: "2023-08-27",
      nombre: "Lucia",
      asistencia: false,
      pagada: false,
    },
    {
      fecha: "2023-09-02",
      nombre: "Lucia",
      asistencia: false,
      pagada: false,
    },
    {
      fecha: "2023-09-03",
      nombre: "Lucia",
      asistencia: false,
      pagada: false,
    },

    //Isabel---Isabel---Isabel---Isabel---Isabel---Isabel---Isabel---Isabel---Isabel---Isabel---Isabel---
    {fecha: "2023-07-13",
      nombre: "Isabel",
      asistencia: true,
      pagada: false,
    },
    {
      fecha: "2023-07-14",
      nombre: "Isabel",
      asistencia: true,
      pagada: false,
    },
    {
      fecha: "2023-07-20",
      nombre: "Isabel",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-07-21",
      nombre: "Isabel",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-07-29",
      nombre: "Isabel",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-07-30",
      nombre: "Isabel",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-08-05",
      nombre: "Isabel",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-08-06",
      nombre: "Isabel",
      asistencia: false,
      pagada: true,
    },

    {
      fecha: "2023-08-12",
      nombre: "Isabel",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-08-13",
      nombre: "Isabel",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-08-19",
      nombre: "Isabel",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-08-20",
      nombre: "Isabel",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-08-26",
      nombre: "Isabel",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-08-27",
      nombre: "Isabel",
      asistencia: false,
      pagada: false,
    },
    {
      fecha: "2023-09-02",
      nombre: "Isabel",
      asistencia: false,
      pagada: false,
    },
    {
      fecha: "2023-09-03",
      nombre: "Isabel",
      asistencia: false,
      pagada: false,
    },
    //Abraham---Abraham---Abraham---Abraham---Abraham---Abraham---Abraham---Abraham---Abraham---
    {
      fecha: "2023-07-13",
      nombre: "Abraham",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-07-14",
      nombre: "Abraham",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-07-20",
      nombre: "Abraham",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-07-21",
      nombre: "Abraham",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-07-29",
      nombre: "Abraham",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-07-30",
      nombre: "Abraham",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-08-05",
      nombre: "Abraham",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-08-06",
      nombre: "Abraham",
      asistencia: false,
      pagada: true,
    },

    {
      fecha: "2023-08-12",
      nombre: "Abraham",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-08-13",
      nombre: "Abraham",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-08-19",
      nombre: "Abraham",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-08-20",
      nombre: "Abraham",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-08-26",
      nombre: "Abraham",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-08-27",
      nombre: "Abraham",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-09-02",
      nombre: "Abraham",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-09-03",
      nombre: "Abraham",
      asistencia: false,
      pagada: true,
    },
    
    //Maximina---Maximina---Maximina---Maximina---Maximina---Maximina---Maximina---Maximina---Maximina---
    {
      fecha: "2023-07-13",
      nombre: "Maximina",
      asistencia: true,
      pagada: false,
    },
    {
      fecha: "2023-07-14",
      nombre: "Maximina",
      asistencia: true,
      pagada: false,
    },
    {
      fecha: "2023-07-20",
      nombre: "Maximina",
      asistencia: true,
      pagada: false,
    },
    {
      fecha: "2023-07-21",
      nombre: "Maximina",
      asistencia: true,
      pagada: false,
    },
    {
      fecha: "2023-07-29",
      nombre: "Maximina",
      asistencia: true,
      pagada: false,
    },
    {
      fecha: "2023-07-30",
      nombre: "Maximina",
      asistencia: true,
      pagada: false,
    },
    {
      fecha: "2023-08-05",
      nombre: "Maximina",
      asistencia: true,
      pagada: false,
    },
    {
      fecha: "2023-08-06",
      nombre: "Maximina",
      asistencia: true,
      pagada: false,
    },

    {
      fecha: "2023-08-12",
      nombre: "Maximina",
      asistencia: true,
      pagada: false,
    },
    {
      fecha: "2023-08-13",
      nombre: "Maximina",
      asistencia: true,
      pagada: false,
    },
    {
      fecha: "2023-08-19",
      nombre: "Maximina",
      asistencia: true,
      pagada: false,
    },
    {
      fecha: "2023-08-20",
      nombre: "Maximina",
      asistencia: true,
      pagada: false,
    },
    {
      fecha: "2023-08-26",
      nombre: "Maximina",
      asistencia: true,
      pagada: false,
    },
    {
      fecha: "2023-08-27",
      nombre: "Maximina",
      asistencia: true,
      pagada: false,
    },
    {
      fecha: "2023-09-02",
      nombre: "Maximina",
      asistencia: true,
      pagada: false,
    },
    {
      fecha: "2023-09-03",
      nombre: "Maximina",
      asistencia: true,
      pagada: false,
    },

    //Alejandra---Alejandra---Alejandra---Alejandra---Alejandra---Alejandra---Alejandra---Alejandra---
    {
      fecha: "2023-07-13",
      nombre: "Alejandra",
      asistencia: true,
      pagada: false,
    },
    {
      fecha: "2023-07-14",
      nombre: "Alejandra",
      asistencia: true,
      pagada: false,
    },
    {
      fecha: "2023-07-20",
      nombre: "Alejandra",
      asistencia: false,
      pagada: false,
    },
    {
      fecha: "2023-07-21",
      nombre: "Alejandra",
      asistencia: false,
      pagada: false,
    },
    {
      fecha: "2023-07-29",
      nombre: "Alejandra",
      asistencia: false,
      pagada: false,
    },
    {
      fecha: "2023-07-30",
      nombre: "Alejandra",
      asistencia: false,
      pagada: false,
    },
    {
      fecha: "2023-08-05",
      nombre: "Alejandra",
      asistencia: true,
      pagada: false,
    },
    {
      fecha: "2023-08-06",
      nombre: "Alejandra",
      asistencia: true,
      pagada: false,
    },

    {
      fecha: "2023-08-12",
      nombre: "Alejandra",
      asistencia: true,
      pagada: false,
    },
    {
      fecha: "2023-08-13",
      nombre: "Alejandra",
      asistencia: false,
      pagada: false,
    },
    {
      fecha: "2023-08-19",
      nombre: "Alejandra",
      asistencia: false,
      pagada: false,
    },
    {
      fecha: "2023-08-20",
      nombre: "Alejandra",
      asistencia: false,
      pagada: false,
    },
    {
      fecha: "2023-08-26",
      nombre: "Alejandra",
      asistencia: false,
      pagada: false,
    },
    {
      fecha: "2023-08-27",
      nombre: "Alejandra",
      asistencia: false,
      pagada: false,
    },
    {
      fecha: "2023-09-02",
      nombre: "Alejandra",
      asistencia: false,
      pagada: false,
    },
    {
      fecha: "2023-09-03",
      nombre: "Alejandra",
      asistencia: false,
      pagada: false,
    },
    //Agustina
    {
      fecha: "2023-07-13",
      nombre: "Agustina",
      asistencia: true,
      pagada: false,
    },
    {
      fecha: "2023-07-14",
      nombre: "Agustina",
      asistencia: true,
      pagada: false,
    },
    {
      fecha: "2023-07-20",
      nombre: "Agustina",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-07-21",
      nombre: "Agustina",
      asistencia: false,
      pagada: true,
    },
    {
      fecha: "2023-07-29",
      nombre: "Agustina",
      asistencia: true,
      pagada: false,
    },
    {
      fecha: "2023-07-30",
      nombre: "Agustina",
      asistencia: true,
      pagada: false,
    },
    {
      fecha: "2023-08-05",
      nombre: "Agustina",
      asistencia: true,
      pagada: false,
    },
    {
      fecha: "2023-08-06",
      nombre: "Agustina",
      asistencia: true,
      pagada: false,
    },
    {
      fecha: "2023-08-12",
      nombre: "Agustina",
      asistencia: true,
      pagada: false,
    },
    {
      fecha: "2023-08-13",
      nombre: "Agustina",
      asistencia: true,
      pagada: false,
    },
    {
      fecha: "2023-08-19",
      nombre: "Agustina",
      asistencia: true,
      pagada: false,
    },
    {
      fecha: "2023-08-20",
      nombre: "Agustina",
      asistencia: true,
      pagada: false,
    },
    {
      fecha: "2023-08-26",
      nombre: "Agustina",
      asistencia: false,
      pagada: false,
    },
    {
      fecha: "2023-08-27",
      nombre: "Agustina",
      asistencia: false,
      pagada: false,
    },
    {
      fecha: "2023-09-02",
      nombre: "Agustina",
      asistencia: false,
      pagada: false,
    },
    {
      fecha: "2023-09-03",
      nombre: "Agustina",
      asistencia: false,
      pagada: false,
    },
  ];

  export default FAENAS;